import IsingModel.PartitionFunctionIso
import IsingModel.TransferMatrix.CubicLayerCylinder
import IsingModel.TransferMatrix.LayerOpenSlab
import Mathlib.Tactic

/-!
# Finite open layer-slab graphs (GJ Section 17.1)

This file connects the open layer-slab transfer sums to the project-level finite
Ising graph API.  The graph has no longitudinal wrap-around edge: each layer
carries a transverse graph `H`, and each selected directed transverse pair
`(x, y) in E` couples layer `i` to layer `i + 1` for `i : Fin n`.

The statements are finite and free-boundary.  They do not prove a physical
interacting spectral window, thermodynamic-limit decay, or the final hyperplane
decay estimate.

## References

* Glimm--Jaffe, *Quantum Physics*, 2nd ed., Section 17.1, pp. 304--306.
* Glimm--Jaffe, *Quantum Physics*, 2nd ed., Section 17.5, pp. 311--312.
-/

namespace IsingModel

namespace TransferMatrix

open scoped BigOperators

variable {S : Type*}

/-! ## Open slab configurations and edge sets -/

/-- A site of a finite open layer slab with `n + 1` longitudinal layers and
finite transverse section `S`. -/
abbrev LayerOpenSlabSite (n : ℕ) (S : Type*) := Fin (n + 1) × S

/-- Reindex a spin configuration on `Fin (n+1) x S` as an open family of layer
configurations. -/
def layerOpenSlabConfigEquiv (n : ℕ) :
    Config (LayerOpenSlabSite n S) ≃ (Fin (n + 1) → LayerState S) where
  toFun σ := fun i x => σ (i, x)
  invFun c := fun ix => c ix.1 ix.2
  left_inv σ := by
    ext ix
    rfl
  right_inv c := by
    ext i x
    rfl

/-- Evaluation of `layerOpenSlabConfigEquiv`. -/
@[simp]
theorem layerOpenSlabConfigEquiv_apply (n : ℕ) (σ : Config (LayerOpenSlabSite n S))
    (i : Fin (n + 1)) (x : S) :
    layerOpenSlabConfigEquiv (S := S) n σ i x = σ (i, x) :=
  rfl

/-- Evaluation of the inverse of `layerOpenSlabConfigEquiv`. -/
@[simp]
theorem layerOpenSlabConfigEquiv_symm_apply (n : ℕ) (c : Fin (n + 1) → LayerState S)
    (i : Fin (n + 1)) (x : S) :
    (layerOpenSlabConfigEquiv (S := S) n).symm c (i, x) = c i x :=
  rfl

/-- Embed a transverse layer into an open slab at longitudinal coordinate `i`. -/
def layerOpenSlabLayerEmbedding (n : ℕ) (i : Fin (n + 1)) :
    S ↪ LayerOpenSlabSite n S where
  toFun x := (i, x)
  inj' := by
    intro x y h
    exact Prod.ext_iff.mp h |>.2

/-- Symmetric pairs copied into different open-slab layers remain different. -/
theorem layerOpenSlabLayerEmbedding_sym2Map_ne_of_ne
    {n : ℕ} {i j : Fin (n + 1)} (hij : i ≠ j) (e f : Sym2 S) :
    (layerOpenSlabLayerEmbedding (S := S) n i).sym2Map e ≠
      (layerOpenSlabLayerEmbedding (S := S) n j).sym2Map f := by
  refine e.ind (fun x y => ?_)
  refine f.ind (fun u v => ?_)
  intro h
  simp only [Function.Embedding.sym2Map_apply, Sym2.map_mk,
    layerOpenSlabLayerEmbedding, Sym2.eq_iff, Prod.ext_iff] at h
  rcases h with h | h
  · exact hij h.1.1
  · exact hij h.1.1

/-- The internal edges of all layers in an open slab. -/
noncomputable def layerOpenSlabInternalEdgeFinset
    [DecidableEq S] (H : SimpleGraph S) [Fintype H.edgeSet] (n : ℕ) :
    Finset (Sym2 (LayerOpenSlabSite n S)) :=
  Finset.univ.biUnion fun i : Fin (n + 1) =>
    H.edgeFinset.map (layerOpenSlabLayerEmbedding (S := S) n i).sym2Map

/-- The transition edge associated to a directed transverse pair `(x, y)` from
layer `i` to layer `i + 1`. -/
def layerOpenSlabTransitionEdge (n : ℕ) (i : Fin n) (xy : S × S) :
    Sym2 (LayerOpenSlabSite n S) :=
  s((i.castSucc, xy.1), (i.succ, xy.2))

/-- The transition edges between consecutive open-slab layers. -/
noncomputable def layerOpenSlabTransitionEdgeFinset
    [DecidableEq S] (E : Finset (S × S)) (n : ℕ) :
    Finset (Sym2 (LayerOpenSlabSite n S)) :=
  (Finset.univ.product E).image fun ixy =>
    layerOpenSlabTransitionEdge (S := S) n ixy.1 ixy.2

/-- All edges of the finite open layer slab. -/
noncomputable def layerOpenSlabEdgeFinset
    [DecidableEq S] (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    (n : ℕ) :
    Finset (Sym2 (LayerOpenSlabSite n S)) :=
  layerOpenSlabInternalEdgeFinset (S := S) H n ∪
    layerOpenSlabTransitionEdgeFinset (S := S) E n

/-- The finite open layer-slab graph generated by the explicit edge finset. -/
noncomputable def layerOpenSlabGraph
    [DecidableEq S] (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    (n : ℕ) :
    SimpleGraph (LayerOpenSlabSite n S) :=
  SimpleGraph.fromEdgeSet (↑(layerOpenSlabEdgeFinset (S := S) H E n) : Set _)

/-! ## Edge-set sanity lemmas -/

/-- Consecutive indices in an open `Fin (n+1)` path are distinct. -/
theorem fin_castSucc_ne_succ {n : ℕ} (i : Fin n) : i.castSucc ≠ i.succ := by
  intro h
  have hv := congr_arg Fin.val h
  simp at hv

/-- Internal layer edges are never diagonal. -/
theorem layerOpenSlabInternalEdge_not_isDiag
    [DecidableEq S] (H : SimpleGraph S) [Fintype H.edgeSet] {n : ℕ}
    {e : Sym2 (LayerOpenSlabSite n S)}
    (he : e ∈ layerOpenSlabInternalEdgeFinset (S := S) H n) :
    ¬ e.IsDiag := by
  classical
  rw [layerOpenSlabInternalEdgeFinset, Finset.mem_biUnion] at he
  rcases he with ⟨i, _hi, hemap⟩
  rcases Finset.mem_map.mp hemap with ⟨eH, heH, rfl⟩
  rw [Function.Embedding.sym2Map_apply, Sym2.isDiag_map
    (layerOpenSlabLayerEmbedding (S := S) n i).injective]
  exact H.not_isDiag_of_mem_edgeFinset heH

/-- A transition edge in an open slab is never diagonal. -/
theorem layerOpenSlabTransitionEdge_not_isDiag
    {n : ℕ} (i : Fin n) (xy : S × S) :
    ¬ (layerOpenSlabTransitionEdge (S := S) n i xy).IsDiag := by
  rw [layerOpenSlabTransitionEdge, Sym2.mk_isDiag_iff, Prod.ext_iff]
  exact fun h => fin_castSucc_ne_succ i h.1

/-- The open transition-edge parametrisation has no duplicate unordered edges. -/
theorem layerOpenSlabTransitionEdge_injective {n : ℕ} :
    Function.Injective
      (fun ixy : Fin n × (S × S) =>
        layerOpenSlabTransitionEdge (S := S) n ixy.1 ixy.2) := by
  intro a b h
  rcases a with ⟨i, x, y⟩
  rcases b with ⟨j, u, v⟩
  simp only [layerOpenSlabTransitionEdge, Sym2.eq_iff] at h
  rcases h with h | h
  · rcases h with ⟨hleft, hright⟩
    have hij : i = j := by
      have hcast : i.castSucc = j.castSucc := (Prod.ext_iff.mp hleft).1
      apply Fin.ext
      simpa using congr_arg Fin.val hcast
    have hxu : x = u := (Prod.ext_iff.mp hleft).2
    have hyv : y = v := (Prod.ext_iff.mp hright).2
    subst hij
    subst hxu
    subst hyv
    rfl
  · rcases h with ⟨hleft, hright⟩
    have hbad : i.castSucc = j.succ := (Prod.ext_iff.mp hleft).1
    have hbad' : i.succ = j.castSucc := (Prod.ext_iff.mp hright).1
    have hv := congr_arg Fin.val hbad
    have hv' := congr_arg Fin.val hbad'
    simp at hv hv'
    omega

/-- Every edge in the transition edge finset is non-diagonal. -/
theorem layerOpenSlabTransitionEdgeFinset_not_isDiag
    [DecidableEq S] (E : Finset (S × S)) {n : ℕ}
    {e : Sym2 (LayerOpenSlabSite n S)}
    (he : e ∈ layerOpenSlabTransitionEdgeFinset (S := S) E n) :
    ¬ e.IsDiag := by
  classical
  rw [layerOpenSlabTransitionEdgeFinset, Finset.mem_image] at he
  rcases he with ⟨ixy, _hmem, rfl⟩
  exact layerOpenSlabTransitionEdge_not_isDiag (S := S) ixy.1 ixy.2

/-- Every edge in the total open-slab edge finset is non-diagonal. -/
theorem layerOpenSlabEdgeFinset_not_isDiag
    [DecidableEq S] (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    {n : ℕ} {e : Sym2 (LayerOpenSlabSite n S)}
    (he : e ∈ layerOpenSlabEdgeFinset (S := S) H E n) :
    ¬ e.IsDiag := by
  classical
  rw [layerOpenSlabEdgeFinset, Finset.mem_union] at he
  rcases he with he | he
  · exact layerOpenSlabInternalEdge_not_isDiag (S := S) H he
  · exact layerOpenSlabTransitionEdgeFinset_not_isDiag (S := S) E he

/-- The graph edge finset is the explicit finite edge set used to define the
finite open layer slab. -/
theorem layerOpenSlabGraph_edgeFinset_eq
    [DecidableEq S] [Finite S] (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    {n : ℕ} :
    (layerOpenSlabGraph (S := S) H E n).edgeFinset =
      layerOpenSlabEdgeFinset (S := S) H E n := by
  letI : Fintype S := Fintype.ofFinite S
  apply Finset.coe_injective
  rw [SimpleGraph.coe_edgeFinset, layerOpenSlabGraph, SimpleGraph.edgeSet_fromEdgeSet]
  ext e
  constructor
  · intro he
    exact he.1
  · intro he
    exact ⟨he, by
      simpa [Sym2.mem_diagSet] using
        layerOpenSlabEdgeFinset_not_isDiag (S := S) H E he⟩

/-! ## Project-level Gibbs API over the explicit open slab graph -/

/-- The project-level Boltzmann weight of the finite open-slab graph, expanded
over the explicit open-slab edge finset and slab sites. -/
theorem boltzmannWeight_layerOpenSlabGraph_eq_edge_field_prod
    [DecidableEq S] [Fintype S]
    (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    (p : IsingParams ℝ) {n : ℕ}
    (σ : Config (LayerOpenSlabSite n S)) :
    boltzmannWeight (layerOpenSlabGraph (S := S) H E n) p σ =
      (∏ e ∈ layerOpenSlabEdgeFinset (S := S) H E n,
        Real.exp (p.β * p.J * edgeSpin (K := ℝ) σ e)) *
      (∏ ix : LayerOpenSlabSite n S,
        Real.exp (p.β * p.h * Spin.sign ℝ (σ ix))) := by
  rw [boltzmannWeight_eq_edge_field_prod,
    layerOpenSlabGraph_edgeFinset_eq (S := S) H E]

/-- The spin product on an explicit open-slab transition edge is the product of
the two endpoint spins in adjacent layers. -/
theorem edgeSpin_layerOpenSlabTransitionEdge
    (p : IsingParams ℝ) {n : ℕ}
    (σ : Config (LayerOpenSlabSite n S)) (i : Fin n) (xy : S × S) :
    Real.exp (p.β * p.J *
      edgeSpin (K := ℝ) σ (layerOpenSlabTransitionEdge (S := S) n i xy)) =
      Real.exp (p.β * p.J *
        (Spin.sign ℝ (σ (i.castSucc, xy.1)) * Spin.sign ℝ (σ (i.succ, xy.2)))) := by
  simp [layerOpenSlabTransitionEdge, edgeSpin]

/-- The transition-edge Boltzmann factors are exactly the indexed open
adjacent-layer transition factors. -/
theorem layerOpenSlabTransitionEdgeFinset_prod_exp
    [DecidableEq S] (E : Finset (S × S)) (p : IsingParams ℝ)
    {n : ℕ} (σ : Config (LayerOpenSlabSite n S)) :
    (∏ e ∈ layerOpenSlabTransitionEdgeFinset (S := S) E n,
      Real.exp (p.β * p.J * edgeSpin (K := ℝ) σ e)) =
      ∏ i : Fin n, ∏ xy ∈ E,
        Real.exp (p.β * p.J *
          (Spin.sign ℝ (σ (i.castSucc, xy.1)) * Spin.sign ℝ (σ (i.succ, xy.2)))) := by
  classical
  unfold layerOpenSlabTransitionEdgeFinset
  rw [Finset.prod_image]
  · change (∏ x ∈ (Finset.univ : Finset (Fin n)) ×ˢ E,
        Real.exp (p.β * p.J * edgeSpin (K := ℝ) σ
          (layerOpenSlabTransitionEdge (S := S) n x.1 x.2))) = _
    rw [Finset.prod_product]
    refine Finset.prod_congr rfl ?_
    intro i _
    refine Finset.prod_congr rfl ?_
    intro xy _
    exact edgeSpin_layerOpenSlabTransitionEdge (S := S) p σ i xy
  · exact (layerOpenSlabTransitionEdge_injective (S := S)).injOn

/-- Internal layer edges and adjacent-layer transition edges are disjoint in an
open slab. -/
theorem layerOpenSlabInternal_transition_disjoint
    [DecidableEq S] (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    {n : ℕ} :
    Disjoint (layerOpenSlabInternalEdgeFinset (S := S) H n)
      (layerOpenSlabTransitionEdgeFinset (S := S) E n) := by
  classical
  rw [Finset.disjoint_iff_ne]
  intro a ha b hb hab
  rw [layerOpenSlabInternalEdgeFinset, Finset.mem_biUnion] at ha
  rcases ha with ⟨i, _hi, ha⟩
  rcases Finset.mem_map.mp ha with ⟨e, _he, rfl⟩
  rw [layerOpenSlabTransitionEdgeFinset, Finset.mem_image] at hb
  rcases hb with ⟨ixy, _hb, rfl⟩
  rcases ixy with ⟨j, xy⟩
  revert hab
  refine e.ind (fun x y hab => ?_)
  simp only [Function.Embedding.sym2Map_apply, Sym2.map_mk,
    layerOpenSlabLayerEmbedding, layerOpenSlabTransitionEdge, Sym2.eq_iff,
    Prod.ext_iff] at hab
  rcases hab with hab | hab
  · have hi_left : i = j.castSucc := by
      simpa [layerOpenSlabLayerEmbedding] using hab.1.1
    have hi_right : i = j.succ := by
      simpa [layerOpenSlabLayerEmbedding] using hab.2.1
    exact fin_castSucc_ne_succ j (hi_left.symm.trans hi_right)
  · have hi_left : i = j.succ := by
      simpa [layerOpenSlabLayerEmbedding] using hab.1.1
    have hi_right : i = j.castSucc := by
      simpa [layerOpenSlabLayerEmbedding] using hab.2.1
    exact fin_castSucc_ne_succ j (hi_right.symm.trans hi_left)

/-- The spin product on an internal copied transverse edge is the transverse
edge spin product in that layer. -/
theorem edgeSpin_layerOpenSlabLayerEmbedding_sym2Map
    {n : ℕ} (σ : Config (LayerOpenSlabSite n S)) (i : Fin (n + 1)) (e : Sym2 S) :
    edgeSpin (K := ℝ) σ
        ((layerOpenSlabLayerEmbedding (S := S) n i).sym2Map e) =
      edgeSpin (K := ℝ) ((layerOpenSlabConfigEquiv (S := S) n σ) i) e := by
  rw [edgeSpin_map_equiv_sym2Map]
  rfl

/-- The internal-edge Boltzmann factors split as a product over layers and
transverse graph edges. -/
theorem layerOpenSlabInternalEdgeFinset_prod_exp
    [DecidableEq S] (H : SimpleGraph S) [Fintype H.edgeSet]
    (p : IsingParams ℝ) (n : ℕ)
    (σ : Config (LayerOpenSlabSite n S)) :
    (∏ e ∈ layerOpenSlabInternalEdgeFinset (S := S) H n,
      Real.exp (p.β * p.J * edgeSpin (K := ℝ) σ e)) =
      ∏ i : Fin (n + 1), ∏ e ∈ H.edgeFinset,
        Real.exp (p.β * p.J *
          edgeSpin (K := ℝ) ((layerOpenSlabConfigEquiv (S := S) n σ) i) e) := by
  classical
  unfold layerOpenSlabInternalEdgeFinset
  rw [Finset.prod_biUnion]
  · refine Finset.prod_congr rfl ?_
    intro i _
    rw [Finset.prod_map]
    refine Finset.prod_congr rfl ?_
    intro e _
    rw [edgeSpin_layerOpenSlabLayerEmbedding_sym2Map]
  · intro i _ j _ hij
    change Disjoint
      (H.edgeFinset.map (layerOpenSlabLayerEmbedding (S := S) n i).sym2Map)
      (H.edgeFinset.map (layerOpenSlabLayerEmbedding (S := S) n j).sym2Map)
    rw [Finset.disjoint_iff_ne]
    intro a ha b hb hab
    rcases Finset.mem_map.mp ha with ⟨e, _he, rfl⟩
    rcases Finset.mem_map.mp hb with ⟨f, _hf, rfl⟩
    exact layerOpenSlabLayerEmbedding_sym2Map_ne_of_ne (S := S) hij e f hab

/-- The one-body field factors over all open-slab sites split layer by layer. -/
theorem layerOpenSlabSite_prod_field_exp
    [Fintype S] (p : IsingParams ℝ) (n : ℕ)
    (σ : Config (LayerOpenSlabSite n S)) :
    (∏ ix : LayerOpenSlabSite n S,
      Real.exp (p.β * p.h * Spin.sign ℝ (σ ix))) =
      ∏ i : Fin (n + 1), ∏ x : S,
        Real.exp (p.β * p.h *
          Spin.sign ℝ (((layerOpenSlabConfigEquiv (S := S) n σ) i) x)) := by
  rw [Fintype.prod_prod_type]
  rfl

/-- The concrete open-slab stack weight expanded into the left endpoint layer
factor and the transition-step factors. -/
theorem layerOpenStackWeight_eq_indexed_edge_field_prod
    [Fintype S] (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    (p : IsingParams ℝ) {n : ℕ}
    (σ : Config (LayerOpenSlabSite n S)) :
    layerOpenStackWeight
        (layerInternalWeight H p) (layerTransitionWeight E p)
        ((layerOpenSlabConfigEquiv (S := S) n) σ) =
      (((∏ e ∈ H.edgeFinset,
          Real.exp (p.β * p.J *
            edgeSpin (K := ℝ) ((layerOpenSlabConfigEquiv (S := S) n σ) 0) e)) *
        ∏ i : Fin n,
          ∏ e ∈ H.edgeFinset,
            Real.exp (p.β * p.J *
              edgeSpin (K := ℝ) ((layerOpenSlabConfigEquiv (S := S) n σ) i.succ) e)) *
        (∏ i : Fin n, ∏ xy ∈ E,
          Real.exp (p.β * p.J *
            (Spin.sign ℝ (((layerOpenSlabConfigEquiv (S := S) n σ) i.castSucc) xy.1) *
              Spin.sign ℝ (((layerOpenSlabConfigEquiv (S := S) n σ) i.succ) xy.2))))) *
      ((∏ x : S,
          Real.exp (p.β * p.h *
            Spin.sign ℝ (((layerOpenSlabConfigEquiv (S := S) n σ) 0) x))) *
        ∏ i : Fin n, ∏ x : S,
            Real.exp (p.β * p.h *
              Spin.sign ℝ (((layerOpenSlabConfigEquiv (S := S) n σ) i.succ) x))) := by
  unfold layerOpenStackWeight pathWeight layerTransferMatrix
  simp_rw [layerInternalWeight_eq_edge_field_prod,
    layerTransitionWeight_eq_prod_exp]
  rw [Finset.prod_mul_distrib, Finset.prod_mul_distrib]
  simp only [layerOpenSlabConfigEquiv_apply]
  ring_nf

/-- The explicit open-slab edge/field Boltzmann product is the concrete
open-slab stack weight. -/
theorem layerOpenSlabEdgeFieldProd_eq_layerOpenStackWeight
    [DecidableEq S] [Fintype S]
    (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    (p : IsingParams ℝ) {n : ℕ}
    (σ : Config (LayerOpenSlabSite n S)) :
    ((∏ e ∈ layerOpenSlabEdgeFinset (S := S) H E n,
        Real.exp (p.β * p.J * edgeSpin (K := ℝ) σ e)) *
      (∏ ix : LayerOpenSlabSite n S,
        Real.exp (p.β * p.h * Spin.sign ℝ (σ ix)))) =
      layerOpenStackWeight
        (layerInternalWeight H p) (layerTransitionWeight E p)
        ((layerOpenSlabConfigEquiv (S := S) n) σ) := by
  classical
  rw [layerOpenStackWeight_eq_indexed_edge_field_prod]
  rw [layerOpenSlabEdgeFinset,
    Finset.prod_union (layerOpenSlabInternal_transition_disjoint (S := S) H E)]
  rw [layerOpenSlabInternalEdgeFinset_prod_exp,
    layerOpenSlabTransitionEdgeFinset_prod_exp (S := S) E p,
    layerOpenSlabSite_prod_field_exp]
  rw [Fin.prod_univ_succ
    (fun i : Fin (n + 1) =>
      ∏ e ∈ H.edgeFinset,
        Real.exp (p.β * p.J *
          edgeSpin (K := ℝ) ((layerOpenSlabConfigEquiv (S := S) n σ) i) e))]
  rw [Fin.prod_univ_succ
    (fun i : Fin (n + 1) =>
      ∏ x : S,
        Real.exp (p.β * p.h *
          Spin.sign ℝ (((layerOpenSlabConfigEquiv (S := S) n σ) i) x)))]
  simp only [layerOpenSlabConfigEquiv_apply]

/-- The project-level Boltzmann weight of the explicit finite open-slab graph is
the concrete open layer-stack weight. -/
theorem boltzmannWeight_layerOpenSlabGraph_eq_layerOpenStackWeight
    [DecidableEq S] [Fintype S]
    (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    (p : IsingParams ℝ) {n : ℕ}
    (σ : Config (LayerOpenSlabSite n S)) :
    boltzmannWeight (layerOpenSlabGraph (S := S) H E n) p σ =
      layerOpenStackWeight
        (layerInternalWeight H p) (layerTransitionWeight E p)
        ((layerOpenSlabConfigEquiv (S := S) n) σ) := by
  rw [boltzmannWeight_layerOpenSlabGraph_eq_edge_field_prod (S := S) H E p σ]
  exact layerOpenSlabEdgeFieldProd_eq_layerOpenStackWeight (S := S) H E p σ

/-- The Ising-weight open-slab partition function. -/
noncomputable def isingLayerOpenSlabPartition
    [Fintype S] [DecidableEq S]
    (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    (p : IsingParams ℝ) (n : ℕ) : ℝ :=
  layerOpenPartition (layerInternalWeight H p) (layerTransitionWeight E p) n

/-- The project-level partition function of the explicit finite open-slab graph
is the concrete Ising open-slab partition function. -/
theorem partitionFunction_layerOpenSlabGraph_eq_isingLayerOpenSlabPartition
    [DecidableEq S] [Fintype S]
    (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    (p : IsingParams ℝ) {n : ℕ} :
    partitionFunction (layerOpenSlabGraph (S := S) H E n) p =
      isingLayerOpenSlabPartition H E p n := by
  unfold partitionFunction isingLayerOpenSlabPartition layerOpenPartition
  exact Fintype.sum_equiv (layerOpenSlabConfigEquiv (S := S) n)
    (fun σ : Config (LayerOpenSlabSite n S) =>
      boltzmannWeight (layerOpenSlabGraph (S := S) H E n) p σ)
    (fun c : Fin (n + 1) → LayerState S =>
      layerOpenStackWeight (layerInternalWeight H p) (layerTransitionWeight E p) c)
    (fun σ => boltzmannWeight_layerOpenSlabGraph_eq_layerOpenStackWeight
      (S := S) H E p σ)

/-- The normalised same-transverse-site two-point function on the concrete
open layer slab. -/
noncomputable def layerOpenSlabSpinTwoPoint
    [Fintype S] [DecidableEq S]
    (u : LayerState S → ℝ) (k : LayerState S → LayerState S → ℝ)
    (x : S) (left sep right : ℕ) : ℝ :=
  layerOpenTwoPoint u k (layerSpinAt x) left sep right

/-- The project-level same-transverse-site two-point correlation on the finite
open-slab graph is the concrete open layer two-point function. -/
theorem correlation_layerOpenSlabGraph_same_transverse_eq_layerOpenSlabSpinTwoPoint
    [DecidableEq S] [Fintype S]
    (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    (p : IsingParams ℝ) (x : S) (left sep right : ℕ) (hsep : 0 < sep) :
    correlation (layerOpenSlabGraph (S := S) H E (left + sep + right)) p
        ({Prod.mk (layerOpenLeftIndex left sep right) x,
          Prod.mk (layerOpenRightIndex left sep right) x} :
            Finset (LayerOpenSlabSite (left + sep + right) S)) =
      layerOpenSlabSpinTwoPoint
        (layerInternalWeight H p) (layerTransitionWeight E p) x
        left sep right := by
  let n := left + sep + right
  have hsite :
      (Prod.mk (layerOpenLeftIndex left sep right) x :
          LayerOpenSlabSite n S) ≠
        Prod.mk (layerOpenRightIndex left sep right) x := by
    intro h
    have hv := congr_arg (fun ix : LayerOpenSlabSite n S => ix.1.val) h
    simp [layerOpenLeftIndex, layerOpenRightIndex] at hv
    omega
  unfold correlation gibbsExpectation
  rw [partitionFunction_layerOpenSlabGraph_eq_isingLayerOpenSlabPartition
    (S := S) H E p]
  unfold isingLayerOpenSlabPartition
  have hsum :
      (∑ σ : Config (LayerOpenSlabSite n S),
          spinProduct
              ({Prod.mk (layerOpenLeftIndex left sep right) x,
                Prod.mk (layerOpenRightIndex left sep right) x} :
                Finset (LayerOpenSlabSite n S)) σ *
            boltzmannWeight (layerOpenSlabGraph (S := S) H E n) p σ)
        =
        ∑ σ : Config (LayerOpenSlabSite n S),
          Spin.sign ℝ (σ (layerOpenLeftIndex left sep right, x))
            * Spin.sign ℝ (σ (layerOpenRightIndex left sep right, x))
            * layerOpenStackWeight
              (layerInternalWeight H p) (layerTransitionWeight E p)
              ((layerOpenSlabConfigEquiv (S := S) n) σ) := by
    refine Finset.sum_congr rfl ?_
    intro σ _
    rw [boltzmannWeight_layerOpenSlabGraph_eq_layerOpenStackWeight
      (S := S) H E p σ]
    simp [spinProduct, Spin.sign, hsite, mul_assoc]
  rw [hsum]
  unfold layerOpenSlabSpinTwoPoint layerOpenTwoPoint layerOpenTwoPointNumerator
    layerOpenMarkedStackWeight layerSpinAt
  rw [div_eq_mul_inv,
    mul_comm (∑ c : Fin (n + 1) → LayerState S,
      Spin.sign ℝ (c (layerOpenLeftIndex left sep right) x) *
        Spin.sign ℝ (c (layerOpenRightIndex left sep right) x) *
        layerOpenStackWeight (layerInternalWeight H p) (layerTransitionWeight E p) c)]
  congr 1
  exact Fintype.sum_equiv (layerOpenSlabConfigEquiv (S := S) n)
    (fun σ : Config (LayerOpenSlabSite n S) =>
      Spin.sign ℝ (σ (layerOpenLeftIndex left sep right, x)) *
        Spin.sign ℝ (σ (layerOpenRightIndex left sep right, x)) *
        layerOpenStackWeight (layerInternalWeight H p) (layerTransitionWeight E p)
          ((layerOpenSlabConfigEquiv (S := S) n) σ))
    (fun c : Fin (n + 1) → LayerState S =>
      Spin.sign ℝ (c (layerOpenLeftIndex left sep right) x) *
        Spin.sign ℝ (c (layerOpenRightIndex left sep right) x) *
        layerOpenStackWeight (layerInternalWeight H p) (layerTransitionWeight E p) c)
    (fun _ => rfl)

/-- A finite open-boundary min-gap certificate gives project-level
same-transverse-site correlation decay on the open slab. -/
theorem correlation_layerOpenSlabGraph_same_transverse_abs_le_of_openMinSpectralGapCertificate
    [DecidableEq S] [Fintype S]
    (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    (p : IsingParams ℝ) (x : S)
    (cert : LayerOpenMinSpectralGapCertificate
      (layerInternalWeight H p) (layerTransitionWeight E p) (layerSpinAt x))
    (left sep right : ℕ) (hsep : 0 < sep) :
    |correlation (layerOpenSlabGraph (S := S) H E (left + sep + right)) p
      ({Prod.mk (layerOpenLeftIndex left sep right) x,
        Prod.mk (layerOpenRightIndex left sep right) x} :
          Finset (LayerOpenSlabSite (left + sep + right) S))|
      ≤ (cert.prefactor / cert.partitionPrefactor) * cert.theta ^ sep := by
  rw [correlation_layerOpenSlabGraph_same_transverse_eq_layerOpenSlabSpinTwoPoint
    (S := S) H E p x left sep right hsep]
  exact layerOpenTwoPoint_abs_le_of_openMinSpectralGapCertificate cert left sep right

/-! ## Cubic transverse open slabs -/

/-- The finite open slab over a cubic transverse box. -/
noncomputable def cubicLayerOpenSlabGraph (d R n : ℕ) :
    SimpleGraph (LayerOpenSlabSite n (CubicLayerSite d R)) :=
  layerOpenSlabGraph (cubicLayerGraph d R) (cubicLayerTransitionPairs d R) n

/-- Cubic transverse boxes inherit finite open-slab correlation decay from an
open min-gap certificate. -/
theorem correlation_cubicLayerOpenSlabGraph_same_transverse_abs_le_of_openCert
    (d R : ℕ) (p : IsingParams ℝ) (x : CubicLayerSite d R)
    (cert : LayerOpenMinSpectralGapCertificate
      (layerInternalWeight (cubicLayerGraph d R) p)
      (layerTransitionWeight (cubicLayerTransitionPairs d R) p)
      (layerSpinAt x))
    (left sep right : ℕ) (hsep : 0 < sep) :
    |correlation (cubicLayerOpenSlabGraph d R (left + sep + right)) p
      ({Prod.mk (layerOpenLeftIndex left sep right) x,
        Prod.mk (layerOpenRightIndex left sep right) x} :
          Finset (LayerOpenSlabSite (left + sep + right) (CubicLayerSite d R)))|
      ≤ (cert.prefactor / cert.partitionPrefactor) * cert.theta ^ sep := by
  rw [cubicLayerOpenSlabGraph]
  exact
    correlation_layerOpenSlabGraph_same_transverse_abs_le_of_openMinSpectralGapCertificate
      (S := CubicLayerSite d R) (cubicLayerGraph d R)
      (cubicLayerTransitionPairs d R) p x cert left sep right hsep

end TransferMatrix

end IsingModel
