import IsingModel.PartitionFunctionIso
import IsingModel.TransferMatrix.LayerCylinder
import Mathlib.Tactic

/-!
# Finite layer-cylinder graphs (GJ §17.1)

This file connects the finite cyclic layer-cylinder weights to the project-level
finite-volume graph API.  The graph is the finite periodic cylinder on
`Fin N × S`: each layer carries a transverse graph `H`, and each selected
directed transverse pair `(x, y) ∈ E` couples `(i, x)` to `(i + 1, y)`.

The open slab/box geometry, Perron--Frobenius theory, thermodynamic limits, and
exponential decay estimates are intentionally left for later files.

## References

* Glimm--Jaffe, *Quantum Physics*, 2nd ed., §17.1, pp. 304--306.
-/

namespace IsingModel

namespace TransferMatrix

open scoped BigOperators

variable {S : Type*}

/-! ## General project-level weight helper -/

/-- Product form of the project-level Boltzmann weight, with both the edge
interaction factors and the one-body field factors displayed. -/
theorem boltzmannWeight_eq_edge_field_prod {ι : Type*} [Fintype ι]
    (G : SimpleGraph ι) [Fintype G.edgeSet]
    (p : IsingParams ℝ) (σ : Config ι) :
    boltzmannWeight G p σ =
      (∏ e ∈ G.edgeFinset, Real.exp (p.β * p.J * edgeSpin (K := ℝ) σ e)) *
      (∏ i : ι, Real.exp (p.β * p.h * Spin.sign ℝ (σ i))) := by
  simp only [boltzmannWeight, hamiltonian, interactionEnergy, externalFieldEnergy]
  rw [← Real.exp_sum (f := fun e => p.β * p.J * edgeSpin (K := ℝ) σ e),
      ← Real.exp_sum (f := fun i => p.β * p.h * Spin.sign ℝ (σ i)),
      ← Real.exp_add]
  congr 1
  simp only [← Finset.mul_sum]
  ring

/-! ## Explicit finite cylinder edge sets -/

/-- Embed a transverse layer into the finite cylinder at longitudinal coordinate
`i`. -/
def layerCylinderLayerEmbedding (N : ℕ) (i : Fin N) :
    S ↪ LayerCylinderSite N S where
  toFun x := (i, x)
  inj' := by
    intro x y h
    exact Prod.ext_iff.mp h |>.2

/-- The internal edges of all layers, obtained by copying `H.edgeFinset` into
each longitudinal slice. -/
noncomputable def layerCylinderInternalEdgeFinset
    [DecidableEq S] (H : SimpleGraph S) [Fintype H.edgeSet] (N : ℕ) :
    Finset (Sym2 (LayerCylinderSite N S)) :=
  Finset.univ.biUnion fun i : Fin N =>
    H.edgeFinset.map (layerCylinderLayerEmbedding (S := S) N i).sym2Map

/-- The transition edge associated to a directed transverse pair `(x, y)` from
layer `i` to layer `i + 1`. -/
def layerCylinderTransitionEdge (N : ℕ) [NeZero N] (i : Fin N) (xy : S × S) :
    Sym2 (LayerCylinderSite N S) :=
  s((i, xy.1), (i + 1, xy.2))

/-- The transition edges between consecutive periodic layers. -/
noncomputable def layerCylinderTransitionEdgeFinset
    [DecidableEq S] (E : Finset (S × S)) (N : ℕ) [NeZero N] :
    Finset (Sym2 (LayerCylinderSite N S)) :=
  (Finset.univ.product E).image fun ixy =>
    layerCylinderTransitionEdge (S := S) N ixy.1 ixy.2

/-- All edges of the finite periodic layer cylinder. -/
noncomputable def layerCylinderEdgeFinset
    [DecidableEq S] (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    (N : ℕ) [NeZero N] :
    Finset (Sym2 (LayerCylinderSite N S)) :=
  layerCylinderInternalEdgeFinset (S := S) H N ∪
    layerCylinderTransitionEdgeFinset (S := S) E N

/-- The finite periodic layer-cylinder graph generated by the explicit edge
finset. -/
noncomputable def layerCylinderGraph
    [DecidableEq S] (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    (N : ℕ) [NeZero N] :
    SimpleGraph (LayerCylinderSite N S) :=
  SimpleGraph.fromEdgeSet (↑(layerCylinderEdgeFinset (S := S) H E N) : Set _)

/-! ## Edge-set sanity lemmas -/

/-- On a cyclic type of size at least two, adding one has no fixed point. -/
theorem fin_add_one_ne_self {N : ℕ} [NeZero N] (hN : 2 ≤ N) (i : Fin N) :
    i + 1 ≠ i := by
  intro h
  have h1 : (1 : Fin N) = 0 := by
    have := congr_arg (fun x : Fin N => x - i) h
    simpa [sub_eq_add_neg, add_assoc, add_comm, add_left_comm] using this
  have hv := congr_arg Fin.val h1
  simp [Nat.mod_eq_of_lt (by omega : 1 < N)] at hv

/-- On a cyclic type of size at least three, two forward steps cannot return to
the starting point. -/
theorem fin_add_two_ne_self {N : ℕ} [NeZero N] (hN : 3 ≤ N) (i : Fin N) :
    i + 1 + 1 ≠ i := by
  intro h
  have h2 : ((1 : Fin N) + 1) = 0 := by
    have := congr_arg (fun x : Fin N => x - i) h
    simpa [sub_eq_add_neg, add_assoc, add_comm, add_left_comm] using this
  have hv := congr_arg Fin.val h2
  simp [Fin.val_add, Nat.mod_eq_of_lt (by omega : 2 < N)] at hv

/-- `fromEdgeSet` has exactly the supplied finite edge set when the supplied
set contains no diagonal unordered pairs. -/
theorem edgeFinset_fromEdgeSet_eq_of_forall_not_isDiag
    {V : Type*} [DecidableEq V] (F : Finset (Sym2 V))
    (hdiag : ∀ e ∈ F, ¬ e.IsDiag) :
    (SimpleGraph.fromEdgeSet (↑F : Set (Sym2 V))).edgeFinset = F := by
  apply Finset.coe_injective
  rw [SimpleGraph.coe_edgeFinset, SimpleGraph.edgeSet_fromEdgeSet]
  ext e
  constructor
  · intro he
    exact he.1
  · intro he
    exact ⟨he, by simpa [Sym2.mem_diagSet] using hdiag e he⟩

/-- Internal layer edges are never diagonal, because they are images of genuine
edges of the transverse graph `H`. -/
theorem layerCylinderInternalEdge_not_isDiag
    [DecidableEq S] (H : SimpleGraph S) [Fintype H.edgeSet] {N : ℕ}
    {e : Sym2 (LayerCylinderSite N S)}
    (he : e ∈ layerCylinderInternalEdgeFinset (S := S) H N) :
    ¬ e.IsDiag := by
  classical
  rw [layerCylinderInternalEdgeFinset, Finset.mem_biUnion] at he
  rcases he with ⟨i, _hi, hemap⟩
  rcases Finset.mem_map.mp hemap with ⟨eH, heH, rfl⟩
  rw [Function.Embedding.sym2Map_apply, Sym2.isDiag_map
    (layerCylinderLayerEmbedding (S := S) N i).injective]
  exact H.not_isDiag_of_mem_edgeFinset heH

/-- A transition edge is never diagonal when the cyclic direction has at least
two sites. -/
theorem layerCylinderTransitionEdge_not_isDiag
    {N : ℕ} [NeZero N] (hN : 2 ≤ N) (i : Fin N) (xy : S × S) :
    ¬ (layerCylinderTransitionEdge (S := S) N i xy).IsDiag := by
  rw [layerCylinderTransitionEdge, Sym2.mk_isDiag_iff, Prod.ext_iff]
  exact fun h => fin_add_one_ne_self hN i h.1.symm

/-- Every edge in the transition edge finset is non-diagonal when the cyclic
direction has at least two sites. -/
theorem layerCylinderTransitionEdgeFinset_not_isDiag
    [DecidableEq S] (E : Finset (S × S)) {N : ℕ} [NeZero N] (hN : 2 ≤ N)
    {e : Sym2 (LayerCylinderSite N S)}
    (he : e ∈ layerCylinderTransitionEdgeFinset (S := S) E N) :
    ¬ e.IsDiag := by
  classical
  rw [layerCylinderTransitionEdgeFinset, Finset.mem_image] at he
  rcases he with ⟨ixy, _hmem, rfl⟩
  exact layerCylinderTransitionEdge_not_isDiag (S := S) hN ixy.1 ixy.2

/-- Every edge in the total cylinder edge finset is non-diagonal when the cyclic
direction has at least two sites. -/
theorem layerCylinderEdgeFinset_not_isDiag
    [DecidableEq S] (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    {N : ℕ} [NeZero N] (hN : 2 ≤ N)
    {e : Sym2 (LayerCylinderSite N S)}
    (he : e ∈ layerCylinderEdgeFinset (S := S) H E N) :
    ¬ e.IsDiag := by
  classical
  rw [layerCylinderEdgeFinset, Finset.mem_union] at he
  rcases he with he | he
  · exact layerCylinderInternalEdge_not_isDiag (S := S) H he
  · exact layerCylinderTransitionEdgeFinset_not_isDiag (S := S) E hN he

/-- The graph edge finset is the explicit finite edge set used to define the
finite periodic layer cylinder. -/
theorem layerCylinderGraph_edgeFinset_eq
    [DecidableEq S] [Finite S] (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    {N : ℕ} [NeZero N] (hN : 2 ≤ N) :
    (layerCylinderGraph (S := S) H E N).edgeFinset =
      layerCylinderEdgeFinset (S := S) H E N :=
by
  letI : Fintype S := Fintype.ofFinite S
  apply Finset.coe_injective
  rw [SimpleGraph.coe_edgeFinset, layerCylinderGraph, SimpleGraph.edgeSet_fromEdgeSet]
  ext e
  constructor
  · intro he
    exact he.1
  · intro he
    exact ⟨he, by
      simpa [Sym2.mem_diagSet] using
        layerCylinderEdgeFinset_not_isDiag (S := S) H E hN he⟩

/-! ## Project-level Gibbs API over the explicit cylinder graph -/

/-- The project-level Boltzmann weight of the finite layer-cylinder graph,
expanded over the explicit cylinder edge finset and the cylinder sites. -/
theorem boltzmannWeight_layerCylinderGraph_eq_edge_field_prod
    [DecidableEq S] [Fintype S]
    (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    (p : IsingParams ℝ) {N : ℕ} [NeZero N] (hN : 2 ≤ N)
    (σ : Config (LayerCylinderSite N S)) :
    boltzmannWeight (layerCylinderGraph (S := S) H E N) p σ =
      (∏ e ∈ layerCylinderEdgeFinset (S := S) H E N,
        Real.exp (p.β * p.J * edgeSpin (K := ℝ) σ e)) *
      (∏ ix : LayerCylinderSite N S,
        Real.exp (p.β * p.h * Spin.sign ℝ (σ ix))) := by
  rw [boltzmannWeight_eq_edge_field_prod,
    layerCylinderGraph_edgeFinset_eq (S := S) H E hN]

/-- The project-level partition function of the finite layer-cylinder graph as
a sum of explicit cylinder edge and field products. -/
theorem partitionFunction_layerCylinderGraph_eq_sum_edge_field_prod
    [DecidableEq S] [Fintype S]
    (H : SimpleGraph S) [Fintype H.edgeSet] (E : Finset (S × S))
    (p : IsingParams ℝ) {N : ℕ} [NeZero N] (hN : 2 ≤ N) :
    partitionFunction (layerCylinderGraph (S := S) H E N) p =
      ∑ σ : Config (LayerCylinderSite N S),
        (∏ e ∈ layerCylinderEdgeFinset (S := S) H E N,
          Real.exp (p.β * p.J * edgeSpin (K := ℝ) σ e)) *
        (∏ ix : LayerCylinderSite N S,
          Real.exp (p.β * p.h * Spin.sign ℝ (σ ix))) := by
  unfold partitionFunction
  refine Finset.sum_congr rfl ?_
  intro σ _
  exact boltzmannWeight_layerCylinderGraph_eq_edge_field_prod
    (S := S) H E p hN σ

/-! ## Layer-weight product forms -/

/-- The one-layer Ising weight as a product of transverse edge factors and
one-body field factors. -/
theorem layerInternalWeight_eq_edge_field_prod
    [Fintype S] (H : SimpleGraph S) [Fintype H.edgeSet] (p : IsingParams ℝ)
    (ω : LayerState S) :
    layerInternalWeight H p ω =
      (∏ e ∈ H.edgeFinset, Real.exp (p.β * p.J * edgeSpin (K := ℝ) ω e)) *
      (∏ x : S, Real.exp (p.β * p.h * Spin.sign ℝ (ω x))) := by
  unfold layerInternalWeight
  rw [Real.exp_add,
    show Real.exp (p.β * p.J * ∑ e ∈ H.edgeFinset, edgeSpin (K := ℝ) ω e)
        = ∏ e ∈ H.edgeFinset,
            Real.exp (p.β * p.J * edgeSpin (K := ℝ) ω e) by
      rw [Finset.mul_sum, Real.exp_sum],
    show Real.exp (p.β * p.h * ∑ x : S, Spin.sign ℝ (ω x))
        = ∏ x : S, Real.exp (p.β * p.h * Spin.sign ℝ (ω x)) by
      rw [Finset.mul_sum, Real.exp_sum]]

/-- The adjacent-layer Ising transition weight as a product over the selected
directed transverse pairs. -/
theorem layerTransitionWeight_eq_prod_exp
    (E : Finset (S × S)) (p : IsingParams ℝ)
    (ω η : LayerState S) :
    layerTransitionWeight E p ω η =
      ∏ xy ∈ E,
        Real.exp (p.β * p.J *
          (Spin.sign ℝ (ω xy.1) * Spin.sign ℝ (η xy.2))) := by
  unfold layerTransitionWeight
  rw [Finset.mul_sum, Real.exp_sum]

end TransferMatrix

end IsingModel
