import IsingModel.Concrete.LatticeGraphCorrelation.Inequalities

/-!
# Cubic tanh-profile lattice-mass corollaries

Small wrapper module for target-level high-temperature `latticeMass`
consequences under the anchored cubic tanh-profile hypotheses used in the
GJ §17.5 Lemma 17.5.2 bridge.
-/

namespace IsingModel
namespace Ambient

/-- **High-temperature lattice-mass lower bound under a cubic tanh-profile
hypothesis**: this checks the anchored cubic active-range theorem generated by
the same tanh-profile hypothesis and then returns the transferred Simon--Lieb
high-temperature lower bound.

The lower-bound conclusion is the existing high-temperature estimate; the
active-range proof is not part of the returned theorem.  The profile hypothesis
is retained as a compatibility condition while the direct concrete
`pseudoMassFromParamsAtPair` wrapper remains too expensive to expose in a new
theorem conclusion.

Reference: Glimm--Jaffe §17.5 pp. 304--306 and Lemma 17.5.2 pp. 311--312. -/
theorem latticeMass_ge_neg_log_of_high_temp_exhaustion_of_cubic_tanh_profile
    {α d : ℕ} {r : ℝ} (hr : 0 < r)
    (Λ : Ambient.Exhaustion (Fin d → ℤ))
    {β J : ℝ} (hJ : 0 ≤ J) (hβ : 0 < β)
    (hlt : β * J * ↑(2 * d) < 1) {z : Fin d → ℤ} (hz : z ≠ 0)
    (hprofile_tanh : pseudoMassG α r (-Real.log (β * J * ↑(2 * d))) ≤
      Real.tanh (β * J) ^ IsingModel.latticeDistance d 0 z) :
    ENNReal.ofReal (-Real.log (β * J * ↑(2 * d))) ≤
      latticeMass d Λ (⟨J, 0, β⟩ : IsingParams ℝ) := by
  have _hactive :
      Ambient.correlationInfinite (IsingModel.latticeGraph d)
        (Ambient.cubicExhaustion d) (⟨J, 0, β⟩ : IsingParams ℝ)
          {(0 : Fin d → ℤ), z} ∈ Set.Ioo (0 : ℝ) 2 :=
    correlationInfinite_cubic_pair_mem_Ioo_zero_two_of_pseudoMassG_le_tanh_pow_dist
      (α := α) hr hJ hβ hlt hz hprofile_tanh
  exact latticeMass_ge_neg_log_of_high_temp_exhaustion Λ hJ hβ hlt

/-- **Positive lattice mass under a cubic tanh-profile hypothesis**: checks the
profile-compatible active-range theorem internally and then applies the
transferred high-temperature positive-mass theorem.

Reference: Glimm--Jaffe §17.5 pp. 304--306 and Lemma 17.5.2 pp. 311--312. -/
theorem latticeMass_pos_of_high_temp_exhaustion_of_cubic_tanh_profile
    {α d : ℕ} (hd : 1 ≤ d) {r : ℝ} (hr : 0 < r)
    (Λ : Ambient.Exhaustion (Fin d → ℤ))
    {β J : ℝ} (hJ : 0 ≤ J) (hβ : 0 < β) (hβJ : 0 < β * J)
    (hlt : β * J * ↑(2 * d) < 1) {z : Fin d → ℤ} (hz : z ≠ 0)
    (hprofile_tanh : pseudoMassG α r (-Real.log (β * J * ↑(2 * d))) ≤
      Real.tanh (β * J) ^ IsingModel.latticeDistance d 0 z) :
    0 < latticeMass d Λ (⟨J, 0, β⟩ : IsingParams ℝ) := by
  have _hactive :
      Ambient.correlationInfinite (IsingModel.latticeGraph d)
        (Ambient.cubicExhaustion d) (⟨J, 0, β⟩ : IsingParams ℝ)
          {(0 : Fin d → ℤ), z} ∈ Set.Ioo (0 : ℝ) 2 :=
    correlationInfinite_cubic_pair_mem_Ioo_zero_two_of_pseudoMassG_le_tanh_pow_dist
      (α := α) hr hJ hβ hlt hz hprofile_tanh
  exact latticeMass_pos_of_high_temp_exhaustion hd Λ hJ hβ hβJ hlt

end Ambient
end IsingModel
