import IsingModel.Concrete.LatticeGraphBED
import IsingModel.Concrete.IntLattice
import IsingModel.Concrete.LatticeGraphCorrelation.Complex
import IsingModel.Concrete.LatticeGraphCorrelation.PerStage
import IsingModel.Concrete.LatticeGraphCorrelation.Magnetization
import IsingModel.Concrete.LatticeGraphCorrelation.TwoPoint
import IsingModel.Concrete.LatticeGraphCorrelation.Translation
import IsingModel.Concrete.LatticeGraphCorrelation.InfiniteVolumeCorrelationInequalities
import IsingModel.Concrete.LatticeGraphCorrelation.LatticeMassFoundation
import IsingModel.Concrete.LatticeGraphCorrelation.LatticeMassHighTemperature
import IsingModel.Concrete.LatticeGraphCorrelation.Inequalities
import IsingModel.Concrete.LatticeGraphCorrelation.HighTemperature
import IsingModel.Concrete.LatticeGraphCorrelation.HighTemperatureBounds
import IsingModel.Concrete.LatticeGraphCorrelation.HighTemperatureCapstones
import IsingModel.Concrete.LatticeGraphCorrelation.JointAnalyticity
import IsingModel.Concrete.LatticeGraphCorrelation.JointRegularity
import IsingModel.Concrete.LatticeGraphCorrelation.CubicPseudoMassBasic
import IsingModel.Concrete.LatticeGraphCorrelation.CubicPseudoMassTanhProfile
import IsingModel.Concrete.LatticeGraphCorrelation.CubicPseudoMassNamedRate
import IsingModel.Concrete.LatticeGraphCorrelation.CubicPseudoMassClusterSummability
import IsingModel.Concrete.LatticeGraphCorrelation.CubicPseudoMassProductSum
import IsingModel.Concrete.LatticeGraphCorrelation.CubicPseudoMass
import IsingModel.Concrete.LatticeGraphCorrelation.TheoremEtaLe1
import IsingModel.Concrete.LatticeGraphCorrelation.SiteIndepMag
import IsingModel.Concrete.LatticeGraphCorrelation.UniformMag
import IsingModel.Concrete.LatticeGraphCorrelation.Base
import IsingModel.Concrete.LatticeGraphCorrelation.FiniteVolumeBasics
import IsingModel.Concrete.LatticeGraphCorrelation.FiniteVolumeCorrelationMonotonicity
import IsingModel.Concrete.LatticeGraphCorrelation.FiniteVolumeExtensions
import IsingModel.Concrete.LatticeGraphCorrelation.FiniteVolumeEnergyBounds
import IsingModel.Concrete.LatticeGraphCorrelation.EnergyClosedForms
import IsingModel.Concrete.LatticeGraphCorrelation.FiniteVolumeCorrelationInequalities
import IsingModel.Concrete.LatticeGraphCorrelation.LambdaCorrelationMonotonicity
import IsingModel.Concrete.LatticeGraphCorrelation.CorrelationExhaustionLimits
import IsingModel.Concrete.LatticeGraphCorrelation.PartitionFreeEnergySuperadditivity
import IsingModel.Concrete.LatticeGraphCorrelation.PartitionExhaustionBounds
import IsingModel.Concrete.LatticeGraphCorrelation.PartitionFreeEnergyMonotonicity
import IsingModel.Concrete.LatticeGraphCorrelation.PartitionFreeEnergyBounds
import IsingModel.Concrete.LatticeGraphCorrelation.FiniteVolumePartition
import IsingModel.Concrete.LatticeGraphCorrelation.FiniteVolumePartitionBounds
import IsingModel.Concrete.LatticeGraphCorrelation.CorrelationSymmetry
import IsingModel.Concrete.LatticeGraphCorrelation.CorrelationDecay
import IsingModel.Concrete.LatticeGraphCorrelation.FreeEnergyAnalyticity
import IsingModel.Concrete.LatticeGraphCorrelation.FreeEnergySpecialCases
import IsingModel.Concrete.LatticeGraphCorrelation.Regularity
import IsingModel.Concrete.LatticeGraphCorrelation.PointwiseRegularity
import IsingModel.Concrete.LatticeGraphCorrelation.MagnetizationPointwiseRegularity
import IsingModel.Concrete.LatticeGraphCorrelation.MayerAnalyticity
import IsingModel.Concrete.LatticeGraphCorrelation.MayerBasicIdentities
import IsingModel.Concrete.LatticeGraphCorrelation.MayerEdgeCases
import IsingModel.Concrete.LatticeGraphCorrelation.MayerExpansionEdgeCases
import IsingModel.Concrete.LatticeGraphCorrelation.MayerEpsilonInfrastructure
import IsingModel.Concrete.LatticeGraphCorrelation.MayerEpsilonPositivity
import IsingModel.Concrete.LatticeGraphCorrelation.MayerFilterConnected
import IsingModel.Concrete.LatticeGraphCorrelation.MayerRecurrenceHasSum
import IsingModel.Concrete.LatticeGraphCorrelation.MayerStrictPositivity
import IsingModel.Concrete.LatticeGraphCorrelation.MayerTanhFerromagneticIff
import IsingModel.Concrete.LatticeGraphCorrelation.MayerTrivialCases
import IsingModel.Concrete.LatticeGraphCorrelation.MayerVdBounds
import IsingModel.Concrete.LatticeGraphCorrelation.MayerVdIff
import IsingModel.Concrete.LatticeGraphCorrelation.MayerVdRegularity
import IsingModel.Concrete.LatticeGraphCorrelation.MagnetizationConvergence
import IsingModel.Concrete.LatticeGraphCorrelation.MagnetizationRegularity
import IsingModel.Concrete.LatticeGraphCorrelation.PartitionFunctionClosedForms
import IsingModel.Concrete.LatticeGraphCorrelation.PartitionFunctionSymmetry
import IsingModel.Concrete.LatticeGraphCorrelation.PartitionFreeEnergyRegularity
import IsingModel.Concrete.LatticeGraphCorrelation.PartitionFunctionGeneralAnalyticity
import IsingModel.Concrete.LatticeGraphCorrelation.PartitionFunctionRegularity
import IsingModel.Concrete.LatticeGraphCorrelation.PartitionFreeEnergyPointwiseRegularity
import IsingModel.Concrete.LatticeGraphCorrelation.PolymerFreeEnergyAnalyticity
import IsingModel.Concrete.LatticeGraphCorrelation.PolymerFreeEnergyBasic
import IsingModel.Concrete.LatticeGraphCorrelation.PolymerFreeEnergyBounds
import IsingModel.Concrete.LatticeGraphCorrelation.PolymerFreeEnergyEpsilonSharpening
import IsingModel.Concrete.LatticeGraphCorrelation.PolymerFreeEnergyHighTemperatureBounds
import IsingModel.Concrete.LatticeGraphCorrelation.PolymerFreeEnergyTanhBounds
import IsingModel.Concrete.LatticeGraphCorrelation.PolymerFreeEnergyTanhSharpening
import IsingModel.Concrete.LatticeGraphCorrelation.SusceptibilityLambda
import IsingModel.Concrete.LatticeGraphCorrelation.SusceptibilityConvergence
import IsingModel.Concrete.LatticeGraphCorrelation.SusceptibilityPointwiseRegularity
import IsingModel.Concrete.LatticeGraphCorrelation.VdPolymerFamiliesAnalyticity
import IsingModel.TranslationInvariance
import IsingModel.PhaseTransition
import IsingModel.Inequalities.FKG
import IsingModel.ComplexAnalyticity
import IsingModel.Concrete.LatticeGraphCorrelation.Peierls
import IsingModel.AmbientComplexAnalyticity
import IsingModel.AmbientFKG
import IsingModel.AmbientLattice.SpecialCases.Legacy

/-!
# Concrete lattice-graph correlation legacy re-export

This module is intentionally a compatibility shim. The former monolithic
theorem bodies have been split into child modules imported above. New code
should import the narrow child modules or
`IsingModel.Concrete.LatticeGraphCorrelation`.
-/
