import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.PseudoMassFromParamsLocalEq
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.PseudoMassFromParamsRegularity
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.FiniteHLSLipschitzPackage
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.PseudoMassFromParamsCompactPackage
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.PseudoMassFromParamsHighTempSandwich
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.DerivativeProfileInputs
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.DerivativeLimitProvider
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.DerivativeLimitProviderCriteria
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.DerivativeLimitProviderFiniteProfile
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.DerivativeLimitProviderInfiniteHLS
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.DerivativeLimitProviderFiniteHLS
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.PseudoMassFromParamsCubicSandwich
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.IncrementCapstone
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.CubicDerivativeProfileLebowitz
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.CubicDerivativeProfileInfiniteVolume
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.CubicUrsellShellSum
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.ShellCovarianceInfiniteVolume
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.ShellCovarianceShellSum
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.CauchyDerivativeBridge
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.CorrelationDerivativeIncrementBridge
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.CorrelationAlongExhaustionDeriv
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.LebowitzAlongExhaustion
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.U4PseudoMassMajorant
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.CapstoneIncrementFromComplexBound
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.CEConditionalCapstone
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.HLSSubstantiveSimonLieb
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.HLSSubstantiveExistingRate
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.HLSSubstantiveCanonicalSummary
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.HLSLatticeMassBridge
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.HLSBridgeFromSimonLieb
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.HLSBridgeUnconditional
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.SharpHLSCapstone
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.GlobalPseudoMass
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.GlobalAllRateComparisonFromPairs
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.PerActivePairRateFromUniformTransfer
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.UniformTransferLargeK
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.UniformSandwich
import IsingModel.Concrete.LatticeGraphCorrelation.Lemma_17_5_2.UniformSandwichCubicTanh

/-!
# GJ §17.5 Lemma 17.5.2 capstone

This compatibility module re-exports the split GJ Lemma 17.5.2 capstone layer,
including the canonical HLS summary and bridge entry points.
-/
