import IsingModel.AmbientLattice.SpecialCases.FreeEnergy
import IsingModel.AmbientLattice.SpecialCases.FreeEnergyAnalyticity
import IsingModel.AmbientLattice.SpecialCases.FreeEnergyAnalyticityHZero
import IsingModel.AmbientLattice.SpecialCases.FreeEnergyAnalyticityOnNhd
import IsingModel.AmbientLattice.SpecialCases.HighTemperature
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBounds
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsExpansion
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsExpansionClosedForms
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsExpansionLowerUpper
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsExpansionLowerUpperFE
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsExpansionVariants
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsExpSharper
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsExpSharperComplete
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsExpSharperSandwich
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsDeviation
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsDeviationContinuity
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsDeviationStrict
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsRatioBounds
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsRatioBoundsBound
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsTripleRatio
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsRatioLogFe
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsRatioLogFeFreeEnergyBound
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsRatioLogFeNonempty
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsDecayCapstones
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureBoundsCorrelationBasic
import IsingModel.AmbientLattice.SpecialCases.HighTemperatureCapstones
import IsingModel.AmbientLattice.SpecialCases.InfiniteVolume
import IsingModel.AmbientLattice.SpecialCases.JointAnalyticity
import IsingModel.AmbientLattice.SpecialCases.JointAnalyticityPartitionFreeEnergy
import IsingModel.AmbientLattice.SpecialCases.JointRegularity
import IsingModel.AmbientLattice.SpecialCases.MayerAnalyticity
import IsingModel.AmbientLattice.SpecialCases.MayerAnalyticityExpansionTerm
import IsingModel.AmbientLattice.SpecialCases.MayerBasicIdentities
import IsingModel.AmbientLattice.SpecialCases.MayerBasicIdentitiesExpansionTerm
import IsingModel.AmbientLattice.SpecialCases.MayerEdgeCases
import IsingModel.AmbientLattice.SpecialCases.MayerEdgeCasesPolymerFreeEnergy
import IsingModel.AmbientLattice.SpecialCases.MayerExpansionEdgeCases
import IsingModel.AmbientLattice.SpecialCases.MayerEpsilonInfrastructure
import IsingModel.AmbientLattice.SpecialCases.MayerEpsilonPositivity
import IsingModel.AmbientLattice.SpecialCases.MayerFilterConnected
import IsingModel.AmbientLattice.SpecialCases.MayerRecurrenceHasSum
import IsingModel.AmbientLattice.SpecialCases.MayerStrictPositivity
import IsingModel.AmbientLattice.SpecialCases.MayerTanhFerromagneticIff
import IsingModel.AmbientLattice.SpecialCases.MayerTrivialCases
import IsingModel.AmbientLattice.SpecialCases.MayerVdBounds
import IsingModel.AmbientLattice.SpecialCases.MayerVdIff
import IsingModel.AmbientLattice.SpecialCases.MayerVdRegularity
import IsingModel.AmbientLattice.SpecialCases.MayerVdRegularityVdPolymer
import IsingModel.AmbientLattice.SpecialCases.MagnetizationConvergence
import IsingModel.AmbientLattice.SpecialCases.MagnetizationRegularity
import IsingModel.AmbientLattice.SpecialCases.PartitionFunctionClosedForms
import IsingModel.AmbientLattice.SpecialCases.PartitionFunctionSymmetry
import IsingModel.AmbientLattice.SpecialCases.PartitionFreeEnergyRegularity
import IsingModel.AmbientLattice.SpecialCases.PartitionFreeEnergyRegularityFE
import IsingModel.AmbientLattice.SpecialCases.PartitionFunctionGeneralAnalyticity
import IsingModel.AmbientLattice.SpecialCases.PartitionFunctionRegularity
import IsingModel.AmbientLattice.SpecialCases.PartitionFunctionRegularityAnalytic
import IsingModel.AmbientLattice.SpecialCases.PartitionFreeEnergyPointwiseRegularity
import IsingModel.AmbientLattice.SpecialCases.PartitionFreeEnergyPointwiseRegularityHZero
import IsingModel.AmbientLattice.SpecialCases.PartitionFreeEnergyPointwiseRegularityFE
import IsingModel.AmbientLattice.SpecialCases.PartitionFreeEnergyPointwiseRegularityPartitionGeneralH
import IsingModel.AmbientLattice.SpecialCases.PolymerFreeEnergyAnalyticity
import IsingModel.AmbientLattice.SpecialCases.PolymerFreeEnergyBasic
import IsingModel.AmbientLattice.SpecialCases.PolymerFreeEnergyBounds
import IsingModel.AmbientLattice.SpecialCases.PolymerFreeEnergyBoundsRegularity
import IsingModel.AmbientLattice.SpecialCases.PolymerFreeEnergyBoundsNonneg
import IsingModel.AmbientLattice.SpecialCases.PolymerFreeEnergyBoundsTanh
import IsingModel.AmbientLattice.SpecialCases.PolymerFreeEnergyEpsilonSharpening
import IsingModel.AmbientLattice.SpecialCases.PolymerFreeEnergyHighTemperatureBounds
import IsingModel.AmbientLattice.SpecialCases.PolymerFreeEnergyTanhBounds
import IsingModel.AmbientLattice.SpecialCases.PolymerFreeEnergyTanhSharpening
import IsingModel.AmbientLattice.SpecialCases.SusceptibilityConvergence
import IsingModel.AmbientLattice.SpecialCases.SusceptibilityPointwiseRegularity
import IsingModel.AmbientLattice.SpecialCases.VdPolymerFamiliesAnalyticity
import IsingModel.AmbientLattice.SpecialCases.VdPolymerFamiliesAnalyticityLog
import IsingModel.AmbientLattice.Analyticity

/-!
# Ambient special-case legacy re-export

This module is intentionally a compatibility shim. The former monolithic
special-case theorem bodies have been split into child modules imported above.
New code should import the narrow child modules or
`IsingModel.AmbientLattice.SpecialCases`.
-/
